Package.json - Change repo name to pulsar-edit
pulsar-edit/flight-manual.atom.io pull request #1
Opened 2022-09-11 08:18 UTC by LandarXT

2022-09-11 08:44 UTC, confused-Techie requested changes
Added a change I think we can implement. Although not sure how others feel about it.

2022-09-11 08:44 UTC, confused-Techie commented on package.json
> +    "url": "https://github.com/pulsar-edit/docs.git"
```suggestion
    "url": "https://github.com/pulsar-edit/flight-manual.atom.io.git"
```

 I know this isn't what was done originally, but makes a lot more sense to me imo.

2022-09-11 09:10 UTC, LandarXT commented
Seems to make sense to me

2022-09-11 09:16 UTC, confused-Techie approved these changes
Super rad, otherwise looks great.

2022-09-11 15:11 UTC, kaosine commented
Honestly this one should just be archived in favor of the docs repo.....

2022-09-11 16:51 UTC, LandarXT commented
I pull requested this one because it looked more complete compared to docs

2022-09-11 16:53 UTC, kaosine commented
It's the same thing, only thing wrong is the system I moved the other to hates the file refs this one had. I've been trying to get around to getting it fixed but working around depression and everything else not giving me the ability to have the focus and energy I need....

2022-09-18 18:13 UTC, softcode589 approved these changes
Simple, no complaints. Easy.

2022-09-25 02:29 UTC, merged